on:
    release: 
        types: 
            - created

jobs:
    deploy-to-dev:
        if: ${{ !contains( github.event.release.tag_name, 'hotfix') }}
        runs-on: ubuntu-latest
        environment: dev
        concurrency: 
            group: dev
            cancel-in-progress: true
        steps:
            - run: echo 'Deployed to DEV'

    deploy-to-npd:
        if: ${{ !contains( github.event.release.tag_name, 'hotfix') }}
        runs-on: ubuntu-latest
        needs: deploy-to-dev
        environment: npd
        concurrency: 
            group: npd
            cancel-in-progress: true
        steps:
            - run: echo 'Deployed to NPD'
            
    deploy-to-prod:
        if: ${{ !contains( github.event.release.tag_name, 'hotfix') }}
        runs-on: ubuntu-latest
        needs: deploy-to-npd
        environment: prod
        concurrency: 
            group: prod
            cancel-in-progress: true
        steps:
            - run: echo 'Deployed to PROD'