on:
    release: 
        types: 
            - published

jobs:
    deploy-to-dev:
        if: ${{ !contains('hotfix', github.event.release.tag_name) }}
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - run: echo 'Deployed to DEV'

    deploy-to-npd:
        if: ${{ !contains('hotfix', github.event.release.tag_name) }}
        runs-on: ubuntu-latest
        needs: deploy-to-dev
        environment: npd
        steps:
            - run: echo 'Deployed to NPD'
            
    deploy-to-prod:
        runs-on: ubuntu-latest
        needs: deploy-to-npd
        environment: prod
        steps:
            - run: echo 'Deployed to PROD'