on:
    push: 
        branches: 
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0  
            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v1
              with:
                versionSpec: '5.x'
            - name: Execute GitVersion
              uses: gittools/actions/gitversion/execute@