on:
    workflow_dispatch: 
        inputs:
            environment:
                description: Environment where this version is going to be deployed
                type: environment
                required: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        concurrency: 
            group: ${{ inputs.environment }}
            cancel-in-progress: true
        steps:
            - run: echo 'Deployed to ${{ inputs.environment }}'