on:
    push: 
        branches: 
            - main
            - hotfix/*

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0  
            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v1
              with:
                versionSpec: '5.x'
            - name: Execute GitVersion
              if: ${{ !contains(github.event.ref, 'hotfix') }}
              uses: gittools/actions/gitversion/execute@v1
            - name: Execute GitVersion (hotfix)
              if: ${{ contains(github.event.ref, 'hotfix') }}
              uses: gittools/actions/gitversion/execute@v1
              with:
                overrideConfig: |
                  commit-message-incrementing=Disabled
            - name: Create tag
              run: git tag ${{ env.semVer }}
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                tag_name: ${{ env.semVer }}
                token: ${{ secrets.RELEASE_TOKEN }}
                generate_release_notes: true
            - name: Create PR from hotfix to main
              if: ${{ contains(github.event.ref, 'hotfix') }}
              run: gh pr create -B main -H ${{ github.event.ref }} --title 'Merge ${{ github.event.ref }} into main' --body 'This PR is created to ensure we do not have regression of the bug fixed by this hotfix. Please analyse if this still applies to main, if it can be merged or if any other actions should be taken. Thanks'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                