on:
    push: 
        branches: 
            - main
            - hotfix/*

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0  
            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v1
              with:
                versionSpec: '5.x'
            - name: Install GitReleaseManager
              uses: gittools/actions/gitreleasemanager/setup@v1
              with:
                versionSpec: '0.17.x'
            - name: Execute GitVersion
              uses: gittools/actions/gitversion/execute@v1
            - name: Create tag
              run: git tag ${{ env.semVer }}
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                tag_name: ${{ env.semVer }}