on:
    push: 
        branches: 
            - main
            - hotfix/*

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0  
            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v1
              with:
                versionSpec: '5.x'
            - name: Execute GitVersion
              if: ${{ !contains(github.event.ref, 'hotfix') }}
              uses: gittools/actions/gitversion/execute@v1
            - name: Execute GitVersion (hotfix)
              if: ${{ contains(github.event.ref, 'hotfix') }}
              uses: gittools/actions/gitversion/execute@v1
              with:
                overrideConfig: |
                  commit-message-incrementing=Disabled
            - name: Create tag
              run: git tag ${{ env.semVer }}
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                tag_name: ${{ env.semVer }}
                token: ${{ secrets.RELEASE_TOKEN }}
                generate_release_notes: true
                